data_process:
  path:
    raw:
      src_train: data/example/raw/train_example.de
      trg_train: data/example/raw/train_example.en
      src_val: data/example/raw/val_example.de
      trg_val: data/example/raw/val_example.en
      src_test: data/example/raw/test_example.de
      trg_test: data/example/raw/test_example.en
    processed:
      train: data/example/processed/train.npz
      val: data/example/processed/val.npz
      test: data/example/processed/test.npz
      src_word2index: data/example/processed/src_word2index.pickle
      src_index2word: data/example/processed/src_index2word.pickle
      trg_word2index: data/example/processed/trg_word2index.pickle
      trg_index2word: data/example/processed/trg_index2word.pickle
  tokenizer: fair
  vocab:
    src:
      max_size: 30000
      min_freq: 1
    trg:
      max_size: 30000
      min_freq: 1
model:
  src_vocab_size: 18560
  trg_vocab_size: 10842
  embed_size: 256
  hidden_size: 512
  num_layers: 2
  bidirectional: True
  rnn_type: LSTM
  attention_type: ScaledDot
  dropout: 0.1
train:
  gpu: 5
  batch_size: 256
  learning_rate: 0.001
  num_epoches: 30
  clip: 5.0